# SETTINGS FILE

# OpenAI API settings
OPENAI_API:
  retry_limit: 3
  rate_limit_sleep_sec: 60
  max_client_timeout_sec: 30

# Model settings
OPENAI_LLM_MODELS:
  GPT4o: 'gpt-4o'
  GPT4o-mini: 'gpt-4o-mini'

# Excel parser settings
CHUNK_COUNT_MAPPING:
  Lowest_Number: 0.15
  Low_Number: 0.30
  Mean_Number: 0.50
  High_Number: 0.70
  Highest_Number: 0.85

CHUNK_SIZE_MAPPING:
  Very_Small: 0.10
  Small: 0.25
  Medium: 0.50
  Large: 0.75
  Very_Large: 0.90

CHUNK_VAR_MAPPING:
  Low_Variation: 10.0
  Average_Variation: 5.0
  High_Variation: 1.0
