# SETTINGS FILE

# Database settings
DATABASE_URL: 'sqlite:///database.db'

# Model settings
MODELS:
  GPT4o: 'gpt-4o'
  GPT4o-mini: 'gpt-4o-mini'
  
# Chunk word count settings
CHUNK_WC_MIN: 20
CHUNK_WC_MAX: 50
TOTAL_WC: 10000
